### ISSUE TITLE
Crash of application if select EUR as Base and Symbol

### ISSUE THREAD

**Issue by ArgonQQ** [mherzner/currency-converter#1]
Hi Michael,

just wanted to try your currency-converter. US & GBP is working great but if I select EUR as Base and Symbol EUR the application crashed. 

![currency-converter](https://user-images.githubusercontent.com/14231786/70330796-8d8ba680-183e-11ea-8964-2706942c7523.gif)

**Comment by mherzner** [comment]
hey marcel, thanks for checking out the project!  
somehow the api can't handle that - i've included an additional filter for now which does remove the base from the list of symbols before firing the request.
